### ISSUE TITLE
copyfile() missed an argument

### ISSUE THREAD

**Issue by w4-jonghoon** [swasun/VQ-VAE-Speech#3]
While exporting features, I got the following error:

```
$ python main.py --export_to_features
[~] The used device is: cpu
[~] The gpu ids are: [0]
[-] The configuration file specified use_cuda=True but cuda isn't available
Downloading http://homepages.inf.ed.ac.uk/jyamagis/release/VCTK-Corpus.tar.gz
Using existing raw folder
Traceback (most recent call last):
  File "main.py", line 126, in <module>
    data_stream = VCTKSpeechStream(configuration, device_configuration.gpu_ids, device_configuration.use_cuda)
  File "/Users/jonghoon.seo/repos/VQ-VAE-Speech/src/dataset/vctk_speech_stream.py", line 44, in __init__
    vctk = VCTK(configuration['data_root'], ratio=configuration['train_val_split'])
  File "/Users/jonghoon.seo/repos/VQ-VAE-Speech/src/dataset/vctk.py", line 84, in __init__
    self.download()
  File "/Users/jonghoon.seo/repos/VQ-VAE-Speech/src/dataset/vctk.py", line 139, in download
    os.path.join(dset_abs_path, "COPYING"),
TypeError: copyfile() missing 1 required positional argument: 'dst'
```

The error is based on this:
([src/dataset/vctk.py:138](https://github.com/swasun/VQ-VAE-Speech/blob/3c537c17465bf59855f0b81d9265354f65016563/src/dataset/vctk.py#L138))
```
        shutil.copyfile(
            os.path.join(dset_abs_path, "COPYING"),
        )
```

I think that copying is unnecessary.
Could you check this error please?

**Comment by derekahuang** [comment]
I also removed this, but I am getting the following error: 
Traceback (most recent call last):
  File "main.py", line 126, in <module>
    data_stream = VCTKSpeechStream(configuration, device_configuration.gpu_ids, device_configuration.use_cuda)
  File "/home/derekhuang/VQ-VAE-Speech/src/dataset/vctk_speech_stream.py", line 54, in __init__
    pin_memory=use_cuda
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Did you ever face this problem?
